#!/bin/sh

echo "Output path: /data/${OUTPUT_PATH}"

content=""
for file in $(ls /data | grep .md)
do
	content="${content}$(cat ${file}) \pagebreak "
done

echo "$content" > /bundle.tmp.md

pandoc -s --template /templates/eisvogel.tex -o /data/${OUTPUT_PATH} $@ /bundle.tmp.md
