#!/bin/sh

mkdir -p /data/out

content=""
for file in $(ls /data | grep .md)
do
	content="${content}$(cat ${file}) \pagebreak "
done

echo "$content" > /data/bundle.tmp.md

pandoc -s --template /templates/eisvogel.tex $@ /data/bundle.tmp.md

rm -f /data/bundle.tmp.md
